import { isPlatformBrowser } from '@angular/common';
import {
	ChangeDetectionStrategy,
	Component,
	DestroyRef,
	OnInit,
	PLATFORM_ID,
	ViewEncapsulation,
	booleanAttribute,
	inject,
	input,
	output,
	signal
} from '@angular/core';
import { takeUntilDestroyed } from '@angular/core/rxjs-interop';
import { resolveHubAccent } from 'ng-hub-ui-utils';
import { fromEvent } from 'rxjs';
import { debounceTime } from 'rxjs/operators';
import { HubFabPosition, HubFabSize, HubSemanticColor } from '../../models/button.types';

/**
 * Floating Action Button component. Renders fixed in the viewport at the given position.
 * Supports circular and extended (pill with label) variants.
 * When collapseOnScroll is true, an extended FAB collapses to icon-only after 50px scroll.
 * Uses inset-inline-* / inset-block-* CSS logical properties for RTL support.
 *
 * The host element *is* the control — a component cannot swap its own tag for a native
 * `<button>` — so it self-advertises `role="button"`, a focusable `tabindex` and
 * Enter/Space activation to stay reachable without a pointer.
 *
 * **Accessibility caveat:** because it reports `role="button"`, a `<hub-fab>` must not be
 * nested inside another interactive element, which would produce an invalid
 * nested-interactive tree. Give it an accessible name (`aria-label`) when the projected
 * content is only an icon.
 */
@Component({
	selector: 'hub-fab',
	standalone: true,
	templateUrl: './fab.component.html',
	styleUrl: './fab.component.scss',
	changeDetection: ChangeDetectionStrategy.OnPush,
	host: {
		class: 'hub-fab',
		role: 'button',
		'[class]': '_hostClass',
		'[style.--hub-fab-accent]': '_accent',
		'[attr.tabindex]': '_tabindex',
		'[attr.aria-disabled]': '_ariaDisabled',
		'(click)': '_handleClick()',
		'(keydown)': '_onKeydown($event)'
	},
	// Exception to emulated encapsulation, for two reasons that both stand on their own.
	//
	// (1) The stylesheet is a public contract. `hub-fab-color($type)` is exported from
	// `ng-hub-ui-buttons/styles` so a consumer can register their own accent, and it emits a
	// plain `.hub-fab-<type>` rule from their global sheet. The six built-in colours are
	// generated by that very same mixin from this stylesheet, so the built-in and the
	// consumer-generated variants only stay interchangeable while both land on the identical
	// plain selector — `:host(.hub-fab-primary)` would out-specify every colour a consumer
	// registers, and re-generating a built-in from their sheet would silently stop working.
	//
	// (2) The rules also dress an element that is not in this component's view.
	// `HubSpeedDialComponent` renders its trigger as `<button class="hub-fab hub-fab-…">`
	// inside its OWN template, and that button is painted by the `.hub-fab` base, size and
	// colour rules of this sheet. Scoped rules would never reach it.
	//
	// Every selector emitted here is namespaced under `.hub-fab*` (plus `.hub-speed-dial
	// .hub-fab`, also this library's own), so nothing the library does not own can match.
	encapsulation: ViewEncapsulation.None
})
export class HubFabComponent implements OnInit {
	color = input<HubSemanticColor>('primary');
	size = input<HubFabSize>('standard');
	/**
	 * Renders the pill variant with a projected label.
	 *
	 * Transformed, so the bare HTML form works: `<hub-fab extended>` passes the empty
	 * string an attribute without a value carries, which an untransformed `input(false)`
	 * rejects at compile time.
	 */
	extended = input(false, { transform: booleanAttribute });
	/** Fixed viewport position. 9-slot grid including center. */
	position = input<HubFabPosition>('bottom-end');
	/** When true, collapses an extended FAB to icon-only on page scroll. */
	collapseOnScroll = input(false, { transform: booleanAttribute });
	disabled = input(false, { transform: booleanAttribute });
	fabClick = output<void>();

	/** Collapse state driven by scroll — only active when extended + collapseOnScroll. */
	protected readonly _collapsed = signal(false);

	private readonly _destroyRef = inject(DestroyRef);
	private readonly _isBrowser = isPlatformBrowser(inject(PLATFORM_ID));

	protected get _hostClass(): string {
		return [
			`hub-fab-${this.color()}`,
			`hub-fab-${this.size()}`,
			`hub-fab-${this.position()}`,
			this.extended() && !this._collapsed() ? 'hub-fab-extended' : '',
			this.disabled() ? 'hub-fab-disabled' : ''
		]
			.filter(Boolean)
			.join(' ');
	}

	/**
	 * The semantic accent consumed by the base `.hub-fab` background slot
	 * (`--hub-fab-accent`). Accepts ANY colour: a bareword (a built-in semantic
	 * name, a host-registered accent or a CSS named colour) resolves to its
	 * `--hub-sys-color-<name>` token with the bareword as the raw fallback, so
	 * unregistered names still paint; a literal (`#hex`, `rgb()`, `oklch()`,
	 * `var(...)`) is passed through unchanged. Built-in `hub-fab-<color>` classes
	 * keep overriding the background, so this slot only paints custom / literal
	 * colours.
	 */
	protected get _accent(): string | null {
		return resolveHubAccent(this.color());
	}

	/**
	 * Keeps the FAB in the tab order (`0`), or takes it out while disabled (`-1`), the
	 * way a native button drops out of it — `pointer-events: none` only hides it from
	 * the pointer.
	 */
	protected get _tabindex(): number {
		return this.disabled() ? -1 : 0;
	}

	/**
	 * Conveys the disabled state to assistive tech, which a custom host tag cannot
	 * express through the native `disabled` attribute.
	 */
	protected get _ariaDisabled(): 'true' | null {
		return this.disabled() ? 'true' : null;
	}

	/**
	 * The host element *is* the button surface — consumers project an icon into it,
	 * not a control — so activation is read here. `disabled` is re-checked in code
	 * because the `pointer-events: none` that backs it is a style: a programmatic
	 * `click()` (or a test) reaches the listener regardless.
	 */
	protected _handleClick(): void {
		if (this.disabled()) return;
		this.fabClick.emit();
	}

	/**
	 * Emulates native button keyboard activation: Enter or Space triggers a click.
	 * Space additionally calls `preventDefault()` to stop the page from scrolling.
	 * @param event The originating keyboard event.
	 */
	protected _onKeydown(event: KeyboardEvent): void {
		if (this.disabled()) return;

		const isSpace = event.key === ' ' || event.key === 'Spacebar';

		if (event.key === 'Enter' || isSpace) {
			if (isSpace) {
				event.preventDefault();
			}

			(event.currentTarget as HTMLElement).click();
		}
	}

	ngOnInit(): void {
		if (!this.collapseOnScroll()) return;

		// There is no scrolling on the server and no `window` to listen on, and the
		// collapsed state is presentational, so the server render simply skips it.
		if (!this._isBrowser) return;

		fromEvent(window, 'scroll', { passive: true })
			.pipe(debounceTime(50), takeUntilDestroyed(this._destroyRef))
			.subscribe(() => {
				this._collapsed.set(window.scrollY > 50);
			});
	}
}
